apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-vault-seal-status
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: check-vault-seal-status
        spec: 
          containers:
            - name: run-seal-check
              image: quay.io/dystewar/vault-unseal:latest
              imagePullPolicy: IfNotPresent
              command: ["bash"]
              args: 
                - /scripts/check-vault-seal.sh
              volumeMounts: 
                - mountPath: /scripts
                  name: script
          volumes:
            - name: script
              configMap:
                name: check-vault-seal-status      