apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
namespace: vault
configMapGenerator:
  - files:
      - scripts/check-vault-seal.yaml
    name: auto-unseal
resources:
  - cronjob.yaml
  - rolebinding.yaml
  - serviceaccount.yaml